### ISSUE TITLE
关于读写集的校验问题

### ISSUE THREAD

**Issue by ClaudeZsb** [yeasy/hyperledger_code_fabric#17]
宝华兄你好，我最近在看系统链码和commiter的validator过程，是想了解如何校验读写集和背书的，现在背书的验证弄明白了，就是关于读写集的校验没有找到那一部分代码，VSCC说负责校验读写集，但是除了对LSCC的特殊校验里有检验之外，私人的chaincode好像没有看到有校验读写集的部分，只有检验背书签名对不对，个数满不满足策略。还望您不吝赐教，谢谢！

**Comment by yeasy** [comment]
See core/ledger/kvledger/txmgmt/validator/statebasedval/state_based_validator.go#162

```go
func (v *Validator) validateTx(txRWSet *rwsetutil.TxRwSet, updates *statedb.UpdateBatch) (peer.TxValidationCode, error) {...}
```

**Comment by ClaudeZsb** [comment]
Thx

**Comment by ClaudeZsb** [comment]
one more question after reading the state_based_validator. For each TransactionAction, only the first ProposalResponse's Payload is stored in it. As a result, the ReadSet that peers will check after receiving an envelope is just the one of several endorsers(if we have). So how could fabric manage the case where the ReadSet differ between each endorser?(ex. some key's version) Thx in advance.

**Comment by ClaudeZsb** [comment]
There is. I saw the ProposalResponse‘s payload check. Just in the protos/utils/txutils.go#114
`func CreateSignedTx(proposal *peer.Proposal, signer msp.SigningIdentity, resps ...*peer.ProposalResponse) (*common.Envelope, error) {
`
Payloads are compared between each other. So if succeed, just put the first Payload in envelope.
Thx.

**Comment by yeasy** [comment]
Sure, and FYI. https://github.com/yeasy/hyperledger_code_fabric/blob/master/core/committer/committer_impl_go.md
