### ISSUE TITLE
could hyperledger support multi Consortiums in a network?  

### ISSUE THREAD

**Issue by fakerjayden** [yeasy/hyperledger_code_fabric#36]
Usually , we define a Consortium in configtx.yaml to produce orderer genesis block? But now , I'm curious whether hyperledger support multi consortiums in a network  by defining these consortiums  in configtx.yaml ? Like this :

Profiles:
   SampleMultiNodeEtcdRaft:
        ......  
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Org1
                - *Org2
            ExampleConsoritium:
                Organizations:
                - * Org3
                - * Org4

**Comment by yeasy** [comment]
Yes, it can.
Consortium is a group of members that they share the same agreement of the resource management, e.g., who can create a channel in the network.
